services:
  - type: web
    name: romskisse
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 8000
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
